# Generated by Django 3.1.2 on 2020-12-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('point', models.IntegerField(default=0)),
                ('disLikedUsers', models.ManyToManyField(blank=True, related_name='question_disliked_users', to=settings.AUTH_USER_MODEL)),
                ('likedUsers', models.ManyToManyField(blank=True, related_name='question_liked_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('point', models.IntegerField(default=0)),
                ('disLikedUsers', models.ManyToManyField(blank=True, related_name='answer_disliked_users', to=settings.AUTH_USER_MODEL)),
                ('likedUsers', models.ManyToManyField(blank=True, related_name='answer_liked_users', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
